# Generated by Django 3.2.7 on 2021-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('birth', models.DateField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
